services:
  sddm:
    build:
      context: .
      dockerfile: Dockerfile
      target: sddm
    tty: true
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    cgroup_parent: docker.slice
    cgroup: private
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    command:  /lib/systemd/systemd log-level=info unit=sysinit.target
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:1
    network_mode: host
